### ISSUE TITLE
use osx with travis, but fix the issue with the git config

### ISSUE THREAD

**Issue by lwjohnst86** [lwjohnst86/prodigenr#100]
(or whatever problem it was...)

**Comment by jdblischak** [comment]
I may be able to help with this. Do you want to setup a build matrix to run on both Linux and macOS? Are you trying to run Git commands during the CI build?

**Comment by lwjohnst86** [comment]
Cool! Yes, that would be nice. When I tried using the osx building on travis, it kept failing for a reason related to not properly set up Git config. I didn't really understand the problem and tried a few things. I ended up just using Linux builds instead. Truthfully, I don't know what the problem was... if you have an idea or know some Travis magic, I would really appreciate the help!
