### ISSUE TITLE
Create a command (or look for a package) to add tags to github

### ISSUE THREAD

**Issue by lwjohnst86** [lwjohnst86/prodigenr#49]
Also for Gitlab?

**Comment by QuLogic** [comment]
Maybe [gh](https://cran.r-project.org/web/packages/gh/) and [gitlabr](https://cran.r-project.org/web/packages/gitlabr/)?

**Comment by lwjohnst86** [comment]
I created an R package for a simple interface to GitHub using gh package: [githubr](https://github.com/lwjohnst86/githubr)

Adding tags should be part of [rostools](https://github.com/rostools/rostools)
