### ISSUE TITLE
Function to add ORCID text/link?

### ISSUE THREAD

**Issue by lwjohnst86** [lwjohnst86/prodigenr#78]
Like to add this: <a href="https://orcid.org/0000-0003-4169-2616" target="orcid.widget" rel="noopener noreferrer" style="vertical-align:top;"><img src="https://orcid.org/sites/default/files/images/orcid_16x16.png" style="width:1em;margin-right:.5em;" alt="ORCID iD icon">orcid.org/0000-0003-4169-2616</a>

but changing the ORCID to what the user wants. (include an option setting to extract it from in Rprofile)

**Comment by jcolomb** [comment]
note that the right way to include an orcid number is: 
"https://orcid.org/0000-0003-4169-2616"

**Comment by lwjohnst86** [comment]
Could use the rorcid package
